// Exporting the population configuration object
export const POPULATION_CONFIG = {
  // Gender options
  genderOptions: [
    { label: 'Male', value: 'Male' },
    { label: 'Female', value: 'Female' },
    { label: 'Other', value: 'Other' },
  ],

  // Age category options
  ageCategoryOptions: [
    { label: 'New born', value: 'New born' },
    { label: 'Child', value: 'Child' },
    { label: 'Teenager', value: 'Teenager' },
    { label: 'Adult', value: 'Adult' },
    { label: 'Senior Citizen', value: 'Senior Citizen' },
  ],

  // Occupation options
  occupationOptions: [
    { label: 'Employed', value: 'Employed' },
    { label: 'Unemployed', value: 'Unemployed' },
  ],

  // Status options
  statusOptions: [
    { label: 'Single', value: 'Single' },
    { label: 'Married', value: 'Married' },
    { label: 'Divorced', value: 'Divorced' },
    { label: 'Widowed', value: 'Widowed' },
  ],

  // Street options
  streetOptions: [
    { label: '1st Laguna Street', value: '1st Laguna Street' },
    { label: '2nd Laguna Street', value: '2nd Laguna Street' },
    { label: 'Abbey Road', value: 'Abbey Road' },
    { label: 'Acacia Street', value: 'Acacia Street' },
    { label: 'Ad Valorem', value: 'Ad Valorem' },
    { label: 'Aganan Street', value: 'Aganan Street' },
    { label: 'Agno', value: 'Agno' },
    { label: 'Agos Lane', value: 'Agos Lane' },
    { label: 'Agusan Street', value: 'Agusan Street' },
    { label: 'Algebra', value: 'Algebra' },
    { label: 'Alimango Street', value: 'Alimango Street' },
    { label: 'Allah', value: 'Allah' },
    { label: 'Almagica Street', value: 'Almagica Street' },
    { label: 'Angat', value: 'Angat' },
    { label: 'Annalisa Street', value: 'Annalisa Street' },
    { label: 'Aplaya', value: 'Aplaya' },
    { label: 'Apo 2nd Street', value: 'Apo 2nd Street' },
    { label: 'Aries Street', value: 'Aries Street' },
    { label: 'Arsenio Street', value: 'Arsenio Street' },
    { label: 'Aster', value: 'Aster' },
    { label: 'Astoria', value: 'Astoria' },
    { label: 'Barit Extension', value: 'Barit Extension' },
    { label: 'Barit Street', value: 'Barit Street' },
    { label: 'Bataan Street', value: 'Bataan Street' },
    { label: 'Bawa Street', value: 'Bawa Street' },
    { label: 'Beethoven Street', value: 'Beethoven Street' },
    { label: 'Biya Street', value: 'Biya Street' },
    { label: 'Blue sky', value: 'Blue sky' },
    { label: 'Bluebird Street', value: 'Bluebird Street' },
    { label: 'Bougainvilla Street', value: 'Bougainvilla Street' },
    { label: 'Bucao Street', value: 'Bucao Street' },
    { label: 'C. Francisco Street', value: 'C. Francisco Street' },
    { label: 'Calaca Street', value: 'Calaca Street' },
    { label: 'Calla Street', value: 'Calla Street' },
    { label: 'Camia Street', value: 'Camia Street' },
    { label: 'Camiling', value: 'Camiling' },
    { label: 'Candido Street', value: 'Candido Street' },
    { label: 'Capital Gain', value: 'Capital Gain' },
    { label: 'Capizan Street', value: 'Capizan Street' },
    { label: 'Capricorn Street', value: 'Capricorn Street' },
    { label: 'Carnation', value: 'Carnation' },
    { label: 'Carnation Street', value: 'Carnation Street' },
    { label: 'Castle Street', value: 'Castle Street' },
    { label: 'Cedar Street', value: 'Cedar Street' },
    { label: 'Celosia Street', value: 'Celosia Street' },
    { label: 'Champaca Street', value: 'Champaca Street' },
    { label: 'Charleville', value: 'Charleville' },
    { label: 'Chestnut', value: 'Chestnut' },
    { label: 'Chestnut Street', value: 'Chestnut Street' },
    { label: 'Chico', value: 'Chico' },
    { label: 'Chopin Street', value: 'Chopin Street' },
    { label: 'Clifton Street', value: 'Clifton Street' },
    { label: 'Cotabato Street', value: 'Cotabato Street' },
    { label: 'Crocus Street', value: 'Crocus Street' },
    { label: 'Cura Lane', value: 'Cura Lane' },
    { label: 'Cypress Street', value: 'Cypress Street' },
    { label: 'D. Muñoz Street', value: 'D. Muñoz Street' },
    { label: 'Daffodils', value: 'Daffodils' },
    { label: 'Dahlia Avenue', value: 'Dahlia Avenue' },
    { label: 'Dahlia Extension', value: 'Dahlia Extension' },
    { label: 'Daisy', value: 'Daisy' },
    { label: 'Daisy Street', value: 'Daisy Street' },
    { label: 'Dalag Street', value: 'Dalag Street' },
    { label: 'Dao Street', value: 'Dao Street' },
    { label: 'De Vega Compound', value: 'De Vega Compound' },
    { label: 'Depot Street', value: 'Depot Street' },
    { label: 'Derby', value: 'Derby' },
    { label: 'Dinar Street', value: 'Dinar Street' },
    { label: 'Doña Angeling Street', value: 'Doña Angeling Street' },
    { label: 'Doña Asuncion Street', value: 'Doña Asuncion Street' },
    { label: 'Doña Consuelo Street', value: 'Doña Consuelo Street' },
    { label: 'Doña Fildela Street', value: 'Doña Fildela Street' },
    { label: 'Doña Juana Street', value: 'Doña Juana Street' },
    { label: 'Doña Juana Street Extension', value: 'Doña Juana Street Extension' },
    { label: 'Doña Sabrina Street', value: 'Doña Sabrina Street' },
    { label: 'Doña Segundo Street', value: 'Doña Segundo Street' },
    { label: 'Doña Teresa Street', value: 'Doña Teresa Street' },
    { label: 'Dollar Street', value: 'Dollar Street' },
    { label: 'Dolores Street', value: 'Dolores Street' },
    { label: 'Don Jose Street', value: 'Don Jose Street' },
    { label: 'Don Julio Gregorio Avenue (proposed)', value: 'Don Julio Gregorio Avenue (proposed)' },
    { label: 'Don Julio Gregorio Street', value: 'Don Julio Gregorio Street' },
    { label: 'Don Raymundo Street', value: 'Don Raymundo Street' },
    { label: 'Don T. Lectura Street', value: 'Don T. Lectura Street' },
    { label: 'Don Vicente Street', value: 'Don Vicente Street' },
    { label: 'Donors', value: 'Donors' },
    { label: 'El Capitan Street', value: 'El Capitan Street' },
    { label: 'Elm', value: 'Elm' },
    { label: 'Emerald Street', value: 'Emerald Street' },
    { label: 'Erwin Street', value: 'Erwin Street' },
    { label: 'Excise', value: 'Excise' },
    { label: 'F. del Mundo Street', value: 'F. del Mundo Street' },
    { label: 'Fercon Street', value: 'Fercon Street' },
    { label: 'Florville Street', value: 'Florville Street' },
    { label: 'Fordham', value: 'Fordham' },
    { label: 'Franchise', value: 'Franchise' },
    { label: 'Franco Street', value: 'Franco Street' },
    { label: 'Fuschia Street', value: 'Fuschia Street' },
    { label: 'Galatian Street', value: 'Galatian Street' },
    { label: 'Garland Street', value: 'Garland Street' },
    { label: 'Genesis Street', value: 'Genesis Street' },
    { label: 'Geometry', value: 'Geometry' },
    { label: 'Georgia', value: 'Georgia' },
    { label: 'Ghana', value: 'Ghana' },
    { label: 'Glenmont Circle', value: 'Glenmont Circle' },
    { label: 'Gold Street', value: 'Gold Street' },
    { label: 'Greece', value: 'Greece' },
    { label: 'Greenland Street', value: 'Greenland Street' },
    { label: 'Greenville Drive', value: 'Greenville Drive' },
    { label: 'Greska', value: 'Greska' },
    { label: 'Guadalupe', value: 'Guadalupe' },
    { label: 'Gumamela Street', value: 'Gumamela Street' },
    { label: 'Guinoo', value: 'Guinoo' },
    { label: 'Hadrian Street', value: 'Hadrian Street' },
    { label: 'Hewitt Avenue', value: 'Hewitt Avenue' },
    { label: 'Highland Court', value: 'Highland Court' },
    { label: 'Hill Crest Street', value: 'Hill Crest Street' },
    { label: 'Himalaya Street', value: 'Himalaya Street' },
    { label: 'Ingleside', value: 'Ingleside' },
    { label: 'Innocent Lane', value: 'Innocent Lane' },
    { label: 'Indigo Street', value: 'Indigo Street' },
    { label: 'Iris Avenue', value: 'Iris Avenue' },
    { label: 'Isla', value: 'Isla' },
    { label: 'Jasmine', value: 'Jasmine' },
    { label: 'Jupiter', value: 'Jupiter' },
    { label: 'Kashmir', value: 'Kashmir' },
    { label: 'Kashmir Avenue', value: 'Kashmir Avenue' },
    { label: 'Keats', value: 'Keats' },
    { label: 'Kendall', value: 'Kendall' },
    { label: 'Kensington', value: 'Kensington' },
    { label: 'La Guelatao Street', value: 'La Guelatao Street' },
    { label: 'Laguna Street', value: 'Laguna Street' },
    { label: 'Laloma Street', value: 'Laloma Street' },
    { label: 'Lana', value: 'Lana' },
    { label: 'Lapu-Lapu Extension', value: 'Lapu-Lapu Extension' },
    { label: 'Lapu-Lapu Street', value: 'Lapu-Lapu Street' },
    { label: 'Lawrence', value: 'Lawrence' },
    { label: 'Lavender', value: 'Lavender' },
    { label: 'Lemon Avenue', value: 'Lemon Avenue' },
    { label: 'Lemon Street', value: 'Lemon Street' },
    { label: 'Liberty', value: 'Liberty' },
    { label: 'Lincoln', value: 'Lincoln' },
    { label: 'Lopez Street', value: 'Lopez Street' },
    { label: 'Lotus', value: 'Lotus' },
    { label: 'Luneta', value: 'Luneta' },
    { label: 'M. Miranda Street', value: 'M. Miranda Street' },
    { label: 'Malabon', value: 'Malabon' },
    { label: 'Maligaya Street', value: 'Maligaya Street' },
    { label: 'Mango Avenue', value: 'Mango Avenue' },
    { label: 'Marina', value: 'Marina' },
    { label: 'Marmalade', value: 'Marmalade' },
    { label: 'Mimosa Avenue', value: 'Mimosa Avenue' },
    { label: 'Myrtle Street', value: 'Myrtle Street' },
    { label: 'Narra Avenue', value: 'Narra Avenue' },
    { label: 'Naples', value: 'Naples' },
    { label: 'Nilo', value: 'Nilo' },
    { label: 'Olympus Street', value: 'Olympus Street' },
    { label: 'Olympus Street', value: 'Olympus Street' },
    { label: 'Orange Avenue', value: 'Orange Avenue' },
    { label: 'Palm Avenue', value: 'Palm Avenue' },
    { label: 'Pandan Extension', value: 'Pandan Extension' },
    { label: 'Park Avenue', value: 'Park Avenue' },
    { label: 'Passion', value: 'Passion' },
    { label: 'Pelegrino', value: 'Pelegrino' },
    { label: 'Philippine Sea', value: 'Philippine Sea' },
    { label: 'Rambutan', value: 'Rambutan' },
    { label: 'Redwood Street', value: 'Redwood Street' },
    { label: 'Rico', value: 'Rico' },
    { label: 'Roosevelt Street', value: 'Roosevelt Street' },
    { label: 'Salvacion', value: 'Salvacion' },
    { label: 'San Pedro', value: 'San Pedro' },
    { label: 'San Pedro Street', value: 'San Pedro Street' },
    { label: 'Santiago Street', value: 'Santiago Street' },
    { label: 'San Jose', value: 'San Jose' },
    { label: 'Santiago Lane', value: 'Santiago Lane' },
    { label: 'San Francisco', value: 'San Francisco' },
    { label: 'San Gabriel', value: 'San Gabriel' },
    { label: 'Santa Monica', value: 'Santa Monica' },
    { label: 'Santos', value: 'Santos' },
    { label: 'Santos Street', value: 'Santos Street' },
    { label: 'Sedge Street', value: 'Sedge Street' },
    { label: 'Sekong', value: 'Sekong' },
    { label: 'Shady Street', value: 'Shady Street' },
    { label: 'Simu', value: 'Simu' },
    { label: 'Skyline', value: 'Skyline' },
    { label: 'Sunshine', value: 'Sunshine' },
    { label: 'Sapphire', value: 'Sapphire' },
    { label: 'Talon', value: 'Talon' },
    { label: 'Tango', value: 'Tango' },
    { label: 'Tantow', value: 'Tantow' },
    { label: 'Terra Nova', value: 'Terra Nova' },
    { label: 'Torre Street', value: 'Torre Street' },
    { label: 'Violetta', value: 'Violetta' },
    { label: 'Violet', value: 'Violet' },
    { label: 'Vitoria', value: 'Vitoria' },
    { label: 'Waverly', value: 'Waverly' },
    { label: 'White Sands', value: 'White Sands' },
    { label: 'Willow Street', value: 'Willow Street' },
    { label: 'Yorba', value: 'Yorba' },
    { label: 'Zigzag', value: 'Zigzag' },
  ] 
}
